In [1]:
# Import packages and libraries
%pip install scikit-learn
%pip install Jinja2
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import seaborn as sns
from pandas import DataFrame
from sklearn.preprocessing import OneHotEncoder

Requirement already satisfied: scikit-learn in c:\users\hinde\appdata\local\programs\python\python312\lib\site-packages (1.4.1.post1)
Requirement already satisfied: numpy<2.0,>=1.19.5 in c:\users\hinde\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in c:\users\hinde\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.12.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\hinde\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\hinde\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (3.3.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: Jinja2 in c:\users\hinde\appdata\local\programs\python\python312\lib\site-packages (3.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\hinde\appdata\local\programs\python\python312\lib\site-packages (from Jinja2) (2.1.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
df = pd.read_csv('df_reduced.csv', index_col=0)
df.transpose()

CaseOrder,1,2,3,4,5,6,7,8,9,10,...,9991,9992,9993,9994,9995,9996,9997,9998,9999,10000
Area,Suburban,Urban,Suburban,Suburban,Rural,Urban,Rural,Urban,Urban,Urban,...,Rural,Urban,Rural,Urban,Urban,Urban,Urban,Rural,Rural,Urban
Children,1,3,3,0,1,3,0,7,0,2,...,0,0,3,1,6,2,4,3,3,8
Age,53,51,53,78,22,76,50,40,48,78,...,69,61,50,83,69,25,87,45,43,70
Income,86575,46805,14370,39741,1209,81999,10456,38319,55586,38965,...,59914,44740,21989,15654,39797,45967,14983,65917,29702,62682
Marital,Divorced,Married,Widowed,Married,Widowed,Never Married,Never Married,Divorced,Widowed,Never Married,...,Never Married,Separated,Married,Married,Separated,Widowed,Widowed,Separated,Divorced,Separated
Gender,Male,Female,Female,Male,Female,Male,Male,Female,Male,Female,...,Female,Male,Female,Male,Male,Male,Male,Female,Male,Female
ReAdmis,No,No,No,No,No,No,No,No,No,No,...,Yes,Yes,Yes,No,No,No,Yes,Yes,Yes,Yes
VitD_levels,19.14,18.94,18.06,16.58,17.44,19.61,14.75,19.69,19.65,18.22,...,15.91,19.25,15.73,18.84,16.6,16.98,18.18,17.13,19.91,18.39
Doc_visits,6,4,4,4,5,6,6,7,6,7,...,4,3,3,4,4,4,5,4,5,5
vitD_supp,0,1,0,0,2,0,0,0,0,2,...,2,0,0,1,2,1,0,0,1,1
Initial_admin,Emergency Admission,Emergency Admission,Elective Admission,Elective Admission,Elective Admission,Observation Admission,Emergency Admission,Observation Admission,Emergency Admission,Emergency Admission,...,Elective Admission,Elective Admission,Emergency Admission,Emergency Admission,Emergency Admission,Emergency Admission,Elective Admission,Elective Admission,Emergency Admission,Observation Admission
HighBlood,Yes,Yes,Yes,No,No,No,Yes,No,No,Yes,...,No,No,Yes,Yes,No,Yes,Yes,Yes,No,No
Stroke,No,No,No,Yes,No,No,No,No,No,No,...,No,Yes,No,No,No,No,No,No,No,No
Complication_risk,Medium,High,Medium,Medium,Low,Medium,Low,Medium,Low,High,...,Medium,Medium,High,High,Medium,Medium,Medium,High,Medium,Low
Overweight,No,Yes,Yes,No,No,Yes,Yes,Yes,Yes,Yes,...,Yes,Yes,No,Yes,No,No,Yes,Yes,Yes,Yes
Arthritis,Yes,No,No,Yes,No,Yes,Yes,No,No,No,...,No,No,Yes,No,Yes,No,Yes,No,No,Yes
Diabetes,Yes,No,Yes,No,No,Yes,Yes,No,No,No,...,No,No,Yes,No,No,No,Yes,No,No,No
Hyperlipidemia,No,No,No,No,Yes,No,Yes,No,Yes,No,...,Yes,Yes,Yes,Yes,No,No,No,No,No,Yes
BackPain,Yes,No,No,No,No,Yes,Yes,No,No,No,...,No,No,No,No,No,No,No,No,Yes,No
Anxiety,Yes,No,No,No,No,No,Yes,No,No,No,...,No,Yes,No,No,No,Yes,No,Yes,No,No
Allergic_rhinitis,Yes,No,No,No,Yes,Yes,No,No,No,Yes,...,No,Yes,Yes,No,No,No,No,Yes,No,Yes
Reflux_esophagitis,No,Yes,No,Yes,No,No,Yes,No,No,Yes,...,Yes,No,Yes,No,Yes,Yes,No,No,No,No
Asthma,Yes,No,No,Yes,No,No,No,No,No,Yes,...,No,Yes,Yes,No,Yes,No,Yes,No,No,No
Initial_days,10.59,15.13,4.77,1.71,1.25,5.96,9.06,14.23,6.18,1.63,...,62.74,56.87,56.62,40.36,37.93,51.56,68.67,70.15,63.36,70.85
S_T_Admission,3,3,2,3,2,4,4,1,3,5,...,3,3,3,6,2,3,3,3,5,4
S_T_Treatment,3,4,4,5,1,5,3,2,3,5,...,4,2,3,6,3,2,3,3,5,3
S_T_Visits,2,3,4,5,3,4,3,2,2,5,...,4,3,4,5,2,2,4,3,3,3
S_Reliability,2,4,4,3,3,4,2,5,3,3,...,4,4,2,3,1,3,2,4,4,2
S_Options,4,4,3,4,5,3,3,4,3,4,...,4,3,4,3,5,4,5,4,4,3
S_Hours_Treatment,3,4,4,5,3,5,4,2,3,2,...,4,3,3,5,3,3,3,2,3,6
S_Staff,3,3,3,5,4,4,5,4,4,3,...,3,4,3,5,4,4,4,3,4,4
S_Active_Listening,4,3,3,5,3,6,5,2,2,2,...,3,3,4,5,2,2,4,2,3,3

# C4 Data Transformation
## Reexpression of categorical variables

- Since the dataset contains several nominal categorical variables, it is essential to re-express these variables in a numerical format to include them in the regression model. This process is known as one-hot encoding, and it involves re-expressing categorical variables as binary variables, a format the regression model can use, by creating dummy variables for each category within a categorical variable. The Pandas library provides a method for performing this transformation using the `pd.get_dummies()` function. This function creates a new binary column for each category in a categorical variable,; 1 indicating the presence of that category and 0 indicating the absence. The original categorical variable is then dropped from the dataset to avoid multicollinearity issues in the regression model.

- Ordinal and binary variables *(Yes/No->1/0)* will be re-expressed as well using pythons `replace` method. 

- (`replace` is apparently being depreciated: "*FutureWarning: Downcasting behavior in replace is deprecated and will be removed in a future version. To retain the old behavior, explicitly call result.infer_objects(copy=False). To opt-in to the future behavior, set pd.set_option('future.no_silent_downcasting, True)`df[binary_vars] = df[binary_vars].replace({'Yes': 1, 'No': 0})*")

In [3]:
# select and show values counts for binary variables to compare berfore and after reexpression
binary_vars = [col for col in df.columns if df[col].isin(['Yes', 'No']).all()]
for col in binary_vars:
    print(df[col].value_counts())

ReAdmis
No     6331
Yes    3669
Name: count, dtype: int64
HighBlood
No     5910
Yes    4090
Name: count, dtype: int64
Stroke
No     8007
Yes    1993
Name: count, dtype: int64
Overweight
Yes    7094
No     2906
Name: count, dtype: int64
Arthritis
No     6426
Yes    3574
Name: count, dtype: int64
Diabetes
No     7262
Yes    2738
Name: count, dtype: int64
Hyperlipidemia
No     6628
Yes    3372
Name: count, dtype: int64
BackPain
No     5886
Yes    4114
Name: count, dtype: int64
Anxiety
No     6785
Yes    3215
Name: count, dtype: int64
Allergic_rhinitis
No     6059
Yes    3941
Name: count, dtype: int64
Reflux_esophagitis
No     5865
Yes    4135
Name: count, dtype: int64
Asthma
No     7107
Yes    2893
Name: count, dtype: int64

In [4]:
# re-expression of binary variables
df[binary_vars] = df[binary_vars].replace({'Yes': 1, 'No': 0})

# check the unique values for the binary variables
for col in binary_vars:
    print(df[col].value_counts())

ReAdmis
0    6331
1    3669
Name: count, dtype: int64
HighBlood
0    5910
1    4090
Name: count, dtype: int64
Stroke
0    8007
1    1993
Name: count, dtype: int64
Overweight
1    7094
0    2906
Name: count, dtype: int64
Arthritis
0    6426
1    3574
Name: count, dtype: int64
Diabetes
0    7262
1    2738
Name: count, dtype: int64
Hyperlipidemia
0    6628
1    3372
Name: count, dtype: int64
BackPain
0    5886
1    4114
Name: count, dtype: int64
Anxiety
0    6785
1    3215
Name: count, dtype: int64
Allergic_rhinitis
0    6059
1    3941
Name: count, dtype: int64
Reflux_esophagitis
0    5865
1    4135
Name: count, dtype: int64
Asthma
0    7107
1    2893
Name: count, dtype: int64

C:\Users\hinde\AppData\Local\Temp\ipykernel_24504\2645779669.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[binary_vars] = df[binary_vars].replace({'Yes': 1, 'No': 0})

- The data dictionary states: "The (Survey) variables represent responses to an eight question survey asking customers to rate the importance of various factors/surfaces on a scale of 1 to 8 (1 most important, 8 least important)" Generally 1 is low and 8 is high in terms of importance and having 1 as most important and 8 as least important is not intuitive, and has caused this analyst confusion. Therefore, we will reverse the scale of survey variables so that 1 is the lowest and 8 is the highest in terms of importance. This will make the interpretation more intuitive in the regression analysis.

In [5]:
# Collect values and compare before and after
survey_vars = ['S_T_Admission', 'S_T_Treatment', 'S_T_Visits', 'S_Reliability', 'S_Options', 'S_Hours_Treatment', 'S_Staff', 'S_Active_Listening']
df[survey_vars].head()

,S_T_Admission,S_T_Treatment,S_T_Visits,S_Reliability,S_Options,S_Hours_Treatment,S_Staff,S_Active_Listening
CaseOrder,,,,,,,,
1,3,3,2,2,4,3,3,4
2,3,4,3,4,4,4,3,3
3,2,4,4,4,3,4,3,3
4,3,5,5,3,4,5,5,5
5,2,1,3,3,5,3,4,3

In [6]:
# reverse the scale of survey variables so that 1 is the lowest and 8 is the highest in terms of importance. and after the change.
df[survey_vars] = df[survey_vars].replace({1: 8, 2: 7, 3: 6, 4: 5, 5: 4, 6: 3, 7: 2, 8: 1})

df[survey_vars].head()

,S_T_Admission,S_T_Treatment,S_T_Visits,S_Reliability,S_Options,S_Hours_Treatment,S_Staff,S_Active_Listening
CaseOrder,,,,,,,,
1,6,6,7,7,5,6,6,5
2,6,5,6,5,5,5,6,6
3,7,5,5,5,6,5,6,6
4,6,4,4,6,5,4,4,4
5,7,8,6,6,4,6,5,6

In [7]:
# reexpress `complication_risk` from categorical variable to numerical variable where 1 is the lowest and 3 is the highest in terms of risk.
# Check values before and after
print(df['Complication_risk'].value_counts())
df['Complication_risk'] = df['Complication_risk'].replace({'Low': 1, 'Medium': 2, 'High': 3}).astype(int)
df['Complication_risk'].value_counts()

Complication_risk
Medium    4517
High      3358
Low       2125
Name: count, dtype: int64

C:\Users\hinde\AppData\Local\Temp\ipykernel_24504\1705884698.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Complication_risk'] = df['Complication_risk'].replace({'Low': 1, 'Medium': 2, 'High': 3}).astype(int)

Complication_risk
2    4517
3    3358
1    2125
Name: count, dtype: int64

In [8]:
#to csv to save progress so far.
df.to_csv('df_for_one_hot.csv', index='CaseOrder')

In [26]:
#read the csv
df = pd.read_csv('df_for_one_hot.csv', index_col=0)
df.head().transpose()

CaseOrder,1,2,3,4,5
Area,Suburban,Urban,Suburban,Suburban,Rural
Children,1,3,3,0,1
Age,53,51,53,78,22
Income,86575,46805,14370,39741,1209
Marital,Divorced,Married,Widowed,Married,Widowed
Gender,Male,Female,Female,Male,Female
ReAdmis,0,0,0,0,0
VitD_levels,19.14,18.94,18.06,16.58,17.44
Doc_visits,6,4,4,4,5
vitD_supp,0,1,0,0,2
Initial_admin,Emergency Admission,Emergency Admission,Elective Admission,Elective Admission,Elective Admission
HighBlood,1,1,1,0,0
Stroke,0,0,0,1,0
Complication_risk,2,3,2,2,1
Overweight,0,1,1,0,0
Arthritis,1,0,0,1,0
Diabetes,1,0,1,0,0
Hyperlipidemia,0,0,0,0,1
BackPain,1,0,0,0,0
Anxiety,1,0,0,0,0
Allergic_rhinitis,1,0,0,0,1
Reflux_esophagitis,0,1,0,1,0
Asthma,1,0,0,1,0
Initial_days,10.59,15.13,4.77,1.71,1.25
S_T_Admission,6,6,7,6,7
S_T_Treatment,6,5,5,4,8
S_T_Visits,7,6,5,4,6
S_Reliability,7,5,5,6,6
S_Options,5,5,6,5,4
S_Hours_Treatment,6,5,5,4,6
S_Staff,6,6,6,4,5
S_Active_Listening,5,6,6,4,6

# One hot encoding

In [27]:
# Using get_dummies to convert nominal variables to 1 and 0 for one-hot encoding and drop the first column to avoid multicollinearity.
nominal_vars = ['Area', 'Marital', 'Gender', 'Initial_admin']
df_encoded = pd.get_dummies(df, columns=nominal_vars, dtype=int, drop_first=True)

In [29]:
# Show the head of the encoded DataFrame
pd.set_option('display.max_columns', None)
df_encoded

,Children,Age,Income,ReAdmis,VitD_levels,Doc_visits,vitD_supp,HighBlood,Stroke,Complication_risk,Overweight,Arthritis,Diabetes,Hyperlipidemia,BackPain,Anxiety,Allergic_rhinitis,Reflux_esophagitis,Asthma,Initial_days,S_T_Admission,S_T_Treatment,S_T_Visits,S_Reliability,S_Options,S_Hours_Treatment,S_Staff,S_Active_Listening,Area_Suburban,Area_Urban,Marital_Married,Marital_Never Married,Marital_Separated,Marital_Widowed,Gender_Male,Gender_Nonbinary,Initial_admin_Emergency Admission,Initial_admin_Observation Admission
CaseOrder,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,1,53,86575,0,19.14,6,0,1,0,2,0,1,1,0,1,1,1,0,1,10.59,6,6,7,7,5,6,6,5,1,0,0,0,0,0,1,0,1,0
2,3,51,46805,0,18.94,4,1,1,0,3,1,0,0,0,0,0,0,1,0,15.13,6,5,6,5,5,5,6,6,0,1,1,0,0,0,0,0,1,0
3,3,53,14370,0,18.06,4,0,1,0,2,1,0,1,0,0,0,0,0,0,4.77,7,5,5,5,6,5,6,6,1,0,0,0,0,1,0,0,0,0
4,0,78,39741,0,16.58,4,0,0,1,2,0,1,0,0,0,0,0,1,1,1.71,6,4,4,6,5,4,4,4,1,0,1,0,0,0,1,0,0,0
5,1,22,1209,0,17.44,5,2,0,0,1,0,0,0,1,0,0,1,0,0,1.25,7,8,6,6,4,6,5,6,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9996,2,25,45967,0,16.98,4,1,1,0,2,0,0,0,0,0,1,0,1,0,51.56,6,7,7,6,5,6,5,7,0,1,0,0,0,1,1,0,1,0
9997,4,87,14983,1,18.18,5,0,1,0,2,1,1,1,0,0,0,0,0,1,68.67,6,6,5,7,4,6,5,5,0,1,0,0,0,1,1,0,0,0
9998,3,45,65917,1,17.13,4,0,1,0,3,1,0,0,0,0,1,1,0,0,70.15,6,6,6,5,5,7,6,7,0,0,0,0,1,0,0,0,0,0
9999,3,43,29702,1,19.91,5,1,0,0,2,1,0,0,0,1,0,0,0,0,63.36,4,4,6,5,5,6,5,6,0,0,0,0,0,0,1,0,1,0
10000,8,70,62682,1,18.39,5,1,0,0,1,1,1,0,1,0,0,1,0,0,70.85,5,6,6,7,6,3,5,6,0,1,0,0,1,0,0,0,0,1

- Noting the shape to be sure extra columns drop: 38 columns

In [31]:
#FINAL CLEAN TRANSFORMED CSV
df_encoded.to_csv('medical_transformed.csv', index='CaseOrder')

--------------------

### G & H: References

- Western Governors University. (2023, December 21). D207 - Medical_clean Dataset. Retrieved from https://lrps.wgu.edu/provision/227079957

- Western Governors University IT Department. (2023). R or Python? How to decide which programming language to learn. Retrieved from https://www.wgu.edu/online-it-degrees/programming-languages/r-or-python.html#

- Datacamp. (2023, December 12). D207 - Exploratory Data Analysis. Retrieved from https://app.datacamp.com/learn/custom-tracks/custom-d207-exploratory-data-analysis 

- Sewell, Dr. (2023). WGU D207 Exploratory Data Analysis [Webinars]. WGU Webex. Accessed December, 2023. https://wgu.webex.com/webappng/sites/wgu/meeting/info/c4aca2eac546482880f1557c938abf40?siteurl=wgu&MTID=me73470c2eac9e863c6f47a3d5b6d2f26 

- Seaborn Developers. (2023). seaborn.scatterplot — seaborn 0.11.2 documentation. Retrieved December 22, 2023, from https://seaborn.pydata.org/generated/seaborn.scatterplot.html

OLD ABOVE _ DELETE?KEEP? as needed.

- Statology. (n.d.). *The Five Assumptions of Multiple Linear Regression*. Statology. Retrieved March 10, 2024, from www.statology.org/multiple-linear-regression-assumptions/

- Pennsylvania State University. (n.d.). *5.3 - The Multiple Linear Regression Model*. STAT 501. Retrieved March 10, 2024, from online.stat.psu.edu/stat501/lesson/5/5.3

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html

In [19]:
# manage memory by using gc.collect() to clear memory
import gc
gc.collect()

0

# Limitations

Beware of the following with your regression analysis:

Overfitting can occur due to limited data points.

Multicollinearity occurs when high association (correlation) with other IVs.

P-values can be unreliable and coefficients swing wildly

Check for pairwise correlations and high VIF (> 10)

Tune your model with as many variables as practical. Forward, backward, stepwise
    regression based on AIC, BIC, etc.
ppoint 5 https://westerngovernorsuniversity-my.sharepoint.com/:p:/g/personal/william_sewell_wgu_edu/ERPQ0YpiQktOl-7YyAVnfLMBR5qeBh2cSv61VaJqe_aHKg?e=FjPhPz

# Errata n notes

I'm wrapping up task 1, and my research question is 'what factors influence the total charge a patient receives'. Total charge has a bimodal distribution that I did a log transform on which helped tremendously. Regarding my final reduced model, the RSE is pretty good, both residual normality and homoscedasticity are mostly there. Both have slight variance from expectations around the tails. For fun I decided to re run my code but filtered my data for patients staying less than a month and it improved my RSE, normality and homoscedasticity. Should I change my research question or keep it broad and just explain the limitations of outlier patients?